/* Generated By:JavaCC: Do not edit this line. scannerConstants.java */
package parser;

public interface scannerConstants {

  int EOF = 0;
  int GT = 7;
  int L_PAREN = 8;
  int R_PAREN = 9;
  int L_CURLY_BRACKET = 10;
  int R__CURLY_BRACKET = 11;
  int L_BRACKET = 12;
  int R_BRACKET = 13;
  int COMMA = 14;
  int EQUALS = 15;
  int PLUS = 16;
  int MINUS = 17;
  int MULTIPLY = 18;
  int NOT = 19;
  int PERIOD = 20;
  int SEMICOLON = 21;
  int AND = 22;
  int IF = 23;
  int NEW = 24;
  int INT = 25;
  int ELSE = 26;
  int VOID = 27;
  int MAIN = 28;
  int TRUE = 29;
  int THIS = 30;
  int CLASS = 31;
  int WHILE = 32;
  int FALSE = 33;
  int STATIC = 34;
  int STRING = 35;
  int RETURN = 36;
  int PUBLIC = 37;
  int LENGTH = 38;
  int EXTENDS = 39;
  int BOOLEAN = 40;
  int PRINT = 41;
  int IDENTIFIER = 42;
  int INTEGER_LIT = 43;
  int INVALID = 44;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"!\"",
    "\".\"",
    "\";\"",
    "\"&&\"",
    "\"if\"",
    "\"new\"",
    "\"int\"",
    "\"else\"",
    "\"void\"",
    "\"main\"",
    "\"true\"",
    "\"this\"",
    "\"class\"",
    "\"while\"",
    "\"false\"",
    "\"static\"",
    "\"String\"",
    "\"return\"",
    "\"public\"",
    "\"length\"",
    "\"extends\"",
    "\"boolean\"",
    "\"System.out.println\"",
    "<IDENTIFIER>",
    "<INTEGER_LIT>",
    "<INVALID>",
  };

}
