/* Generated By:JavaCC: Do not edit this line. parserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int L_PAREN = 13;
  /** RegularExpression Id. */
  int R_PAREN = 14;
  /** RegularExpression Id. */
  int L_BRACE = 15;
  /** RegularExpression Id. */
  int R_BRACE = 16;
  /** RegularExpression Id. */
  int L_BRACKET = 17;
  /** RegularExpression Id. */
  int R_BRACKET = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int EQUALS = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;
  /** RegularExpression Id. */
  int MULTIPLY = 23;
  /** RegularExpression Id. */
  int NOT = 24;
  /** RegularExpression Id. */
  int PERIOD = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int NEW = 29;
  /** RegularExpression Id. */
  int INT = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int VOID = 32;
  /** RegularExpression Id. */
  int MAIN = 33;
  /** RegularExpression Id. */
  int TRUE = 34;
  /** RegularExpression Id. */
  int THIS = 35;
  /** RegularExpression Id. */
  int CLASS = 36;
  /** RegularExpression Id. */
  int WHILE = 37;
  /** RegularExpression Id. */
  int FALSE = 38;
  /** RegularExpression Id. */
  int STATIC = 39;
  /** RegularExpression Id. */
  int STRING = 40;
  /** RegularExpression Id. */
  int RETURN = 41;
  /** RegularExpression Id. */
  int PUBLIC = 42;
  /** RegularExpression Id. */
  int LENGTH = 43;
  /** RegularExpression Id. */
  int EXTENDS = 44;
  /** RegularExpression Id. */
  int BOOLEAN = 45;
  /** RegularExpression Id. */
  int PRINT = 46;
  /** RegularExpression Id. */
  int IDENTIFIER = 47;
  /** RegularExpression Id. */
  int INTEGER_LIT = 48;
  /** RegularExpression Id. */
  int INVALID = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"!\"",
    "\".\"",
    "\";\"",
    "\"&&\"",
    "\"if\"",
    "\"new\"",
    "\"int\"",
    "\"else\"",
    "\"void\"",
    "\"main\"",
    "\"true\"",
    "\"this\"",
    "\"class\"",
    "\"while\"",
    "\"false\"",
    "\"static\"",
    "\"String\"",
    "\"return\"",
    "\"public\"",
    "\"length\"",
    "\"extends\"",
    "\"boolean\"",
    "\"System.out.println\"",
    "<IDENTIFIER>",
    "<INTEGER_LIT>",
    "<INVALID>",
  };

}
