/* Generated By:JavaCC: Do not edit this line. parser.java */
package parser;

import syntax.*;
import java.util.ArrayList;

public class parser implements parserConstants {

  static final public Program Goal() throws ParseException {
  MainClass main;
  ArrayList <ClassDecl> classes = new ArrayList <ClassDecl>();
  ClassDecl currentClass;
    main = MainClass();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      currentClass = ClassDeclaration();
     classes.add(currentClass);
    }
    jj_consume_token(0);
   {if (true) return new Program(main, classes);}
    throw new Error("Missing return statement in function");
  }

  static final public MainClass MainClass() throws ParseException {
  Token t1; Token t2;
  Statement statement;
  Identifier i1; Identifier i2;
    t1 = jj_consume_token(CLASS);
    t2 = jj_consume_token(IDENTIFIER);
   i1 = new Identifier(t2.beginLine, t2.beginColumn, t2.toString());
    jj_consume_token(L_BRACE);
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(VOID);
    jj_consume_token(MAIN);
    jj_consume_token(L_PAREN);
    jj_consume_token(STRING);
    jj_consume_token(L_BRACKET);
    jj_consume_token(R_BRACKET);
    t2 = jj_consume_token(IDENTIFIER);
   i2 = new Identifier(t2.beginLine, t2.beginColumn, t2.toString());
    jj_consume_token(R_PAREN);
    jj_consume_token(L_BRACE);
    statement = Statement();
    jj_consume_token(R_BRACE);
    jj_consume_token(R_BRACE);
   {if (true) return new MainClass(t1.beginLine, t1.beginColumn, i1, i2, statement);}
    throw new Error("Missing return statement in function");
  }

  static final public ClassDecl ClassDeclaration() throws ParseException {
  ClassDecl currentClass;
    if (jj_2_1(3)) {
      currentClass = SimpleClass();
     {if (true) return currentClass;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
        currentClass = ExtendsClass();
     {if (true) return currentClass;}
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public SimpleClassDecl SimpleClass() throws ParseException {
  Token t;
  Identifier i;
  ArrayList <VarDecl> vars = new ArrayList<VarDecl>();
  ArrayList <MethodDecl> methods = new ArrayList<MethodDecl>();
    jj_consume_token(CLASS);
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(L_BRACE);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case BOOLEAN:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      VarDeclaration(vars);
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      MethodDeclaration(methods);
    }
    jj_consume_token(R_BRACE);
   i = new Identifier(t.beginLine, t.beginColumn, t.toString()); {if (true) return new SimpleClassDecl(i, vars, methods);}
    throw new Error("Missing return statement in function");
  }

  static final public ExtendingClassDecl ExtendsClass() throws ParseException {
  Token t;
  Identifier i1; Identifier i2;
  ArrayList <VarDecl> vars = new ArrayList<VarDecl>();
  ArrayList <MethodDecl> methods = new ArrayList<MethodDecl>();
    jj_consume_token(CLASS);
    t = jj_consume_token(IDENTIFIER);
   i1 = new Identifier(t.beginLine, t.beginColumn, t.toString());
    jj_consume_token(EXTENDS);
    t = jj_consume_token(IDENTIFIER);
   i2 = new Identifier(t.beginLine, t.beginColumn, t.toString());
    jj_consume_token(L_BRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case BOOLEAN:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      VarDeclaration(vars);
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      MethodDeclaration(methods);
    }
    jj_consume_token(R_BRACE);
   {if (true) return new ExtendingClassDecl(i1, i2, vars, methods);}
    throw new Error("Missing return statement in function");
  }

  static final public void VarDeclaration(ArrayList<VarDecl> vars) throws ParseException {
  Type type;
  Token t;
  Identifier i;
    type = Type();
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(SEMICOLON);
   i = new Identifier(t.beginLine, t.beginColumn, t.toString()); vars.add(new VarDecl(type, i));
  }

  static final public void MethodDeclaration(ArrayList<MethodDecl> methods) throws ParseException {
  Type type;
  Token t;
  Identifier i;
  ArrayList <Formal> formals = new ArrayList <Formal>();
  ArrayList <VarDecl> vars = new ArrayList <VarDecl>();
  ArrayList <Statement> statements = new ArrayList <Statement>();
  Statement currentStatement;
  Expression e;
    jj_consume_token(PUBLIC);
    type = Type();
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(L_PAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case BOOLEAN:
    case IDENTIFIER:
      FormalParameterList(formals);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(R_PAREN);
    jj_consume_token(L_BRACE);
    label_6:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_6;
      }
      VarDeclaration(vars);
    }
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case L_BRACE:
      case IF:
      case WHILE:
      case PRINT:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_7;
      }
      currentStatement = Statement();
     statements.add(currentStatement);
    }
    jj_consume_token(RETURN);
    e = Expression();
    jj_consume_token(SEMICOLON);
    jj_consume_token(R_BRACE);
    i = new Identifier(t.beginLine, t.beginColumn, t.toString());
    methods.add(new MethodDecl(type, i, formals, vars, statements, e));
  }

  static final public void FormalParameterList(ArrayList<Formal> formals) throws ParseException {
  Formal f;
    f = FormalParameter();
   formals.add(f);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_8;
      }
      f = FormalParameterRest();
     formals.add(f);
    }
  }

  static final public Formal FormalParameter() throws ParseException {
  Type type;
  Token t;
  Identifier i;
    type = Type();
    t = jj_consume_token(IDENTIFIER);
    i = new Identifier(t.beginLine, t.beginColumn, t.toString());
    {if (true) return new Formal(type, i);}
    throw new Error("Missing return statement in function");
  }

  static final public Formal FormalParameterRest() throws ParseException {
  Formal f;
    jj_consume_token(COMMA);
    f = FormalParameter();
   {if (true) return f;}
    throw new Error("Missing return statement in function");
  }

  static final public Type Type() throws ParseException {
  Type t;
    if (jj_2_3(2)) {
      t = ArrayType();
     {if (true) return t;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOLEAN:
        t = BooleanType();
     {if (true) return t;}
        break;
      case INT:
        t = IntType();
     {if (true) return t;}
        break;
      case IDENTIFIER:
        t = IdentifierType();
     {if (true) return t;}
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public IntArrayType ArrayType() throws ParseException {
    jj_consume_token(INT);
    jj_consume_token(L_BRACKET);
    jj_consume_token(R_BRACKET);
   {if (true) return Type.THE_INT_ARRAY_TYPE;}
    throw new Error("Missing return statement in function");
  }

  static final public BooleanType BooleanType() throws ParseException {
    jj_consume_token(BOOLEAN);
   {if (true) return Type.THE_BOOLEAN_TYPE;}
    throw new Error("Missing return statement in function");
  }

  static final public IntegerType IntType() throws ParseException {
    jj_consume_token(INT);
   {if (true) return Type.THE_INTEGER_TYPE;}
    throw new Error("Missing return statement in function");
  }

  static final public IdentifierType IdentifierType() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
   {if (true) return new IdentifierType(t.beginLine, t.beginColumn, t.toString());}
    throw new Error("Missing return statement in function");
  }

  static final public Statement Statement() throws ParseException {
  Statement statement;
  ArrayList<Statement> statements = new ArrayList<Statement>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case L_BRACE:
      BlockStatements(statements);
     {if (true) return statements.get(0);}
      break;
    default:
      jj_la1[10] = jj_gen;
      if (jj_2_4(2)) {
        statement = AssignmentStatement();
     {if (true) return statement;}
      } else if (jj_2_5(2)) {
        statement = ArrayAssignment();
     {if (true) return statement;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IF:
          statement = IfStatement();
     {if (true) return statement;}
          break;
        case WHILE:
          statement = WhileStatement();
     {if (true) return statement;}
          break;
        case PRINT:
          statement = PrintStatement();
     {if (true) return statement;}
          break;
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public void BlockStatements(ArrayList<Statement> statements) throws ParseException {
  Statement statement;
    jj_consume_token(L_BRACE);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case L_BRACE:
      case IF:
      case WHILE:
      case PRINT:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_9;
      }
      statement = Statement();
     statements.add(statement);
    }
    jj_consume_token(R_BRACE);
  }

  static final public If IfStatement() throws ParseException {
  Token t;
  Expression e;
  Statement s1 ; Statement s2;
    jj_consume_token(IF);
    jj_consume_token(L_PAREN);
    e = Expression();
    jj_consume_token(R_PAREN);
    s1 = Statement();
    jj_consume_token(ELSE);
    s2 = Statement();
   {if (true) return new If(e, s1, s2);}
    throw new Error("Missing return statement in function");
  }

  static final public While WhileStatement() throws ParseException {
  Token t;
  Expression e;
  Statement s;
    t = jj_consume_token(WHILE);
    jj_consume_token(L_PAREN);
    e = Expression();
    jj_consume_token(R_PAREN);
    s = Statement();
   {if (true) return new While(t.beginLine, t.beginColumn, e, s);}
    throw new Error("Missing return statement in function");
  }

  static final public Print PrintStatement() throws ParseException {
  Token t;
  Expression e;
    t = jj_consume_token(PRINT);
    jj_consume_token(L_PAREN);
    e = Expression();
    jj_consume_token(R_PAREN);
    jj_consume_token(SEMICOLON);
   {if (true) return new Print(t.beginLine, t.beginColumn, e);}
    throw new Error("Missing return statement in function");
  }

  static final public Assign AssignmentStatement() throws ParseException {
  Token t;
  Identifier i;
  Expression e;
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(EQUALS);
    e = Expression();
    jj_consume_token(SEMICOLON);
    i = new Identifier(t.beginLine, t.beginColumn, t.toString());
    {if (true) return new Assign(t.beginLine, t.beginColumn, i, e);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayAssign ArrayAssignment() throws ParseException {
  Token t;
  Identifier i;
  Expression e1; Expression e2;
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(L_BRACKET);
    e1 = Expression();
    jj_consume_token(R_BRACKET);
    jj_consume_token(EQUALS);
    e2 = Expression();
    jj_consume_token(SEMICOLON);
    i = new Identifier(t.beginLine, t.beginColumn, t.toString());
    {if (true) return new ArrayAssign(t.beginLine, t.beginColumn, i, e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public Expression Expression() throws ParseException {
  Expression e;
    if (jj_2_6(2147483647)) {
      e = And();
     {if (true) return e;}
    } else if (jj_2_7(2147483647)) {
      e = LessThan();
     {if (true) return e;}
    } else if (jj_2_8(2147483647)) {
      e = Plus();
     {if (true) return e;}
    } else if (jj_2_9(2147483647)) {
      e = Minus();
     {if (true) return e;}
    } else if (jj_2_10(2147483647)) {
      e = Multiplication();
     {if (true) return e;}
    } else if (jj_2_11(2147483647)) {
      e = ArrayLookup();
     {if (true) return e;}
    } else if (jj_2_12(2147483647)) {
      e = ArrayLength();
     {if (true) return e;}
    } else if (jj_2_13(2147483647)) {
      e = MethodCall();
     {if (true) return e;}
    } else if (jj_2_14(2147483647)) {
      e = ParenExpression();
     {if (true) return e;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case L_PAREN:
      case NOT:
      case NEW:
      case TRUE:
      case THIS:
      case FALSE:
      case IDENTIFIER:
      case INTEGER_LIT:
        e = PrimaryExpression();
     {if (true) return e;}
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public And And() throws ParseException {
  Expression e1; Expression e2;
    e1 = PrimaryExpression();
    jj_consume_token(AND);
    e2 = PrimaryExpression();
   {if (true) return new And(e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public LessThan LessThan() throws ParseException {
  Expression e1; Expression e2;
    e1 = PrimaryExpression();
    jj_consume_token(LT);
    e2 = PrimaryExpression();
   {if (true) return new LessThan(e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public Plus Plus() throws ParseException {
  Expression e1; Expression e2;
    e1 = PrimaryExpression();
    jj_consume_token(PLUS);
    e2 = PrimaryExpression();
   {if (true) return new Plus(e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public Minus Minus() throws ParseException {
  Expression e1; Expression e2;
    e1 = PrimaryExpression();
    jj_consume_token(MINUS);
    e2 = PrimaryExpression();
   {if (true) return new Minus(e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public Times Multiplication() throws ParseException {
  Expression e1; Expression e2;
    e1 = PrimaryExpression();
    jj_consume_token(MULTIPLY);
    e2 = PrimaryExpression();
   {if (true) return new Times(e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayLookup ArrayLookup() throws ParseException {
  Expression e1; Expression e2;
    e1 = PrimaryExpression();
    jj_consume_token(L_BRACKET);
    e2 = PrimaryExpression();
    jj_consume_token(R_BRACKET);
   {if (true) return new ArrayLookup(e1, e2);}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayLength ArrayLength() throws ParseException {
  Expression e;
    e = PrimaryExpression();
    jj_consume_token(PERIOD);
    jj_consume_token(LENGTH);
   {if (true) return new ArrayLength(e);}
    throw new Error("Missing return statement in function");
  }

  static final public Call MethodCall() throws ParseException {
  Expression e;
  Token t;
  Identifier i;
  ArrayList <Expression> expList = new ArrayList <Expression>();
    e = PrimaryExpression();
    jj_consume_token(PERIOD);
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(L_PAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case L_PAREN:
    case NOT:
    case NEW:
    case TRUE:
    case THIS:
    case FALSE:
    case IDENTIFIER:
    case INTEGER_LIT:
      expList = ExpressionList();
      break;
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    jj_consume_token(R_PAREN);
    i = new Identifier(t.beginLine, t.beginColumn, t.toString());
    {if (true) return new Call (t.beginLine, t.beginColumn, e, i, expList);}
    throw new Error("Missing return statement in function");
  }

  static final public Expression ParenExpression() throws ParseException {
  Expression e;
    jj_consume_token(L_PAREN);
    e = Expression();
    jj_consume_token(R_PAREN);
    {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression PrimaryExpression() throws ParseException {
  Expression e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LIT:
      e = IntegerLiteral();
     {if (true) return e;}
      break;
    case TRUE:
      e = True();
     {if (true) return e;}
      break;
    case FALSE:
      e = False();
     {if (true) return e;}
      break;
    case IDENTIFIER:
      e = IdentifierExpression();
     {if (true) return e;}
      break;
    case THIS:
      e = This();
     {if (true) return e;}
      break;
    default:
      jj_la1[15] = jj_gen;
      if (jj_2_15(2)) {
        e = NewArray();
     {if (true) return e;}
      } else if (jj_2_16(2)) {
        e = NewObject();
     {if (true) return e;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NOT:
          e = Not();
     {if (true) return e;}
          break;
        case L_PAREN:
          e = BracketExpression();
     {if (true) return e;}
          break;
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  static final public IntegerLiteral IntegerLiteral() throws ParseException {
  Token t;
    t = jj_consume_token(INTEGER_LIT);
   {if (true) return new IntegerLiteral (Integer.valueOf(t.toString()));}
    throw new Error("Missing return statement in function");
  }

  static final public True True() throws ParseException {
  Token t;
    t = jj_consume_token(TRUE);
   {if (true) return new True(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  static final public False False() throws ParseException {
  Token t;
    t = jj_consume_token(FALSE);
   {if (true) return new False(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  static final public IdentifierExp IdentifierExpression() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
   {if (true) return new IdentifierExp(t.beginLine, t.beginColumn, t.toString());}
    throw new Error("Missing return statement in function");
  }

  static final public This This() throws ParseException {
  Token t;
    t = jj_consume_token(THIS);
   {if (true) return new This(t.beginLine, t.beginColumn);}
    throw new Error("Missing return statement in function");
  }

  static final public NewArray NewArray() throws ParseException {
  Expression e;
    jj_consume_token(NEW);
    jj_consume_token(INT);
    jj_consume_token(L_BRACKET);
    e = Expression();
    jj_consume_token(R_BRACKET);
   {if (true) return new NewArray(e);}
    throw new Error("Missing return statement in function");
  }

  static final public NewObject NewObject() throws ParseException {
  Token t;
  Identifier i;
    jj_consume_token(NEW);
    t = jj_consume_token(IDENTIFIER);
    jj_consume_token(L_PAREN);
    jj_consume_token(R_PAREN);
    i = new Identifier(t.beginLine, t.beginColumn, t.toString());
    {if (true) return new NewObject(i);}
    throw new Error("Missing return statement in function");
  }

  static final public Not Not() throws ParseException {
  Token t;
  Expression e;
    t = jj_consume_token(NOT);
    e = Expression();
   {if (true) return new Not(t.beginLine, t.beginColumn, e);}
    throw new Error("Missing return statement in function");
  }

  static final public Expression BracketExpression() throws ParseException {
  Expression e;
    jj_consume_token(L_PAREN);
    e = Expression();
    jj_consume_token(R_PAREN);
   {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Expression> ExpressionList() throws ParseException {
  ArrayList<Expression> expList = new ArrayList<Expression>();
  Expression e;
    e = Expression();
   expList.add(e);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_10;
      }
      e = ExpressionRest();
     expList.add(e);
    }
   {if (true) return expList;}
    throw new Error("Missing return statement in function");
  }

  static final public Expression ExpressionRest() throws ParseException {
  Expression e;
    jj_consume_token(COMMA);
    e = Expression();
   {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_3R_57() {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_56() {
    if (jj_scan_token(L_PAREN)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(R_PAREN)) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(AND)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_scan_token(L_PAREN)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(L_BRACKET)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(R_BRACKET)) return true;
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(PERIOD)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_scan_token(INT)) return true;
    if (jj_scan_token(L_BRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(PERIOD)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_3R_20()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_scan_token(THIS)) return true;
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_3R_59()) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_3R_56()) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(L_BRACKET)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_3R_58()) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_3R_55()) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(PERIOD)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(L_PAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_60()) jj_scanpos = xsp;
    if (jj_scan_token(R_PAREN)) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_3R_57()) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(MULTIPLY)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_3R_54()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_3R_53()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_3R_52()) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(LT)) return true;
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(PERIOD)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_3R_51()) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(AND)) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_3R_50()) return true;
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_49()) return true;
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(L_BRACKET)) return true;
    if (jj_3R_16()) return true;
    if (jj_scan_token(R_BRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    if (jj_3R_63()) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_3R_48()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_scan_token(CLASS)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(L_BRACE)) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_scan_token(INTEGER_LIT)) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    if (jj_3R_17()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_62()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(MULTIPLY)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_3R_47()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_scan_token(L_PAREN)) return true;
    if (jj_3R_17()) return true;
    if (jj_scan_token(R_PAREN)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3_16() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(L_BRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3_15() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_3R_45()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_44()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_3R_42()) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(EQUALS)) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_3R_41()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(L_PAREN)) return true;
    if (jj_scan_token(R_PAREN)) return true;
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(LT)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public parserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[18];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x40000000,0x0,0x40000000,0x0,0x40000000,0x10008000,0x80000,0x40000000,0x8000,0x10000000,0x10008000,0x21002000,0x21002000,0x0,0x1002000,0x80000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x10,0x10,0xa000,0x400,0xa000,0x400,0xa000,0xc020,0x0,0xa000,0x0,0x4020,0xc020,0x1804c,0x1804c,0x1804c,0x0,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[16];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new parserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new parserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public parser(parserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(parserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[50];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 18; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 50; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 16; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

                     }
