/* Generated By:JavaCC: Do not edit this line. parserConstants.java */
package parser;

public interface parserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int MULTI_LINE_COMMENT = 10;
  int GT = 11;
  int LT = 12;
  int L_PAREN = 13;
  int R_PAREN = 14;
  int L_BRACE = 15;
  int R_BRACE = 16;
  int L_BRACKET = 17;
  int R_BRACKET = 18;
  int COMMA = 19;
  int EQUALS = 20;
  int PLUS = 21;
  int MINUS = 22;
  int MULTIPLY = 23;
  int NOT = 24;
  int PERIOD = 25;
  int SEMICOLON = 26;
  int AND = 27;
  int IF = 28;
  int NEW = 29;
  int INT = 30;
  int ELSE = 31;
  int VOID = 32;
  int MAIN = 33;
  int TRUE = 34;
  int THIS = 35;
  int CLASS = 36;
  int WHILE = 37;
  int FALSE = 38;
  int STATIC = 39;
  int STRING = 40;
  int RETURN = 41;
  int PUBLIC = 42;
  int LENGTH = 43;
  int EXTENDS = 44;
  int BOOLEAN = 45;
  int PRINT = 46;
  int IDENTIFIER = 47;
  int INTEGER_LIT = 48;
  int INVALID = 49;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"!\"",
    "\".\"",
    "\";\"",
    "\"&&\"",
    "\"if\"",
    "\"new\"",
    "\"int\"",
    "\"else\"",
    "\"void\"",
    "\"main\"",
    "\"true\"",
    "\"this\"",
    "\"class\"",
    "\"while\"",
    "\"false\"",
    "\"static\"",
    "\"String\"",
    "\"return\"",
    "\"public\"",
    "\"length\"",
    "\"extends\"",
    "\"boolean\"",
    "\"System.out.println\"",
    "<IDENTIFIER>",
    "<INTEGER_LIT>",
    "<INVALID>",
  };

}
